// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs_57b9DuOUWHjEUzAvdlrBv6Y-sKU5BY',
    appId: '1:132842422466:web:5c2ede25d28a29b7097b5b',
    messagingSenderId: '132842422466',
    projectId: 'guido-test-20e43',
    authDomain: 'guido-test-20e43.firebaseapp.com',
    storageBucket: 'guido-test-20e43.appspot.com',
    measurementId: 'G-X2LC2WK9JZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOqLT_lbcz2N19lI0QI76eoEEC9p7UjbM',
    appId: '1:132842422466:android:dc1d1aecbbd6e598097b5b',
    messagingSenderId: '132842422466',
    projectId: 'guido-test-20e43',
    storageBucket: 'guido-test-20e43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_HSXTmcaWv70epKO7Fbd9TNvVusysSUI',
    appId: '1:132842422466:ios:7219c6c198715a58097b5b',
    messagingSenderId: '132842422466',
    projectId: 'guido-test-20e43',
    storageBucket: 'guido-test-20e43.appspot.com',
    iosClientId: '132842422466-infpvh0ipp42260n38b7m0825b71nu0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.guido',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_HSXTmcaWv70epKO7Fbd9TNvVusysSUI',
    appId: '1:132842422466:ios:7219c6c198715a58097b5b',
    messagingSenderId: '132842422466',
    projectId: 'guido-test-20e43',
    storageBucket: 'guido-test-20e43.appspot.com',
    iosClientId: '132842422466-infpvh0ipp42260n38b7m0825b71nu0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.guido',
  );
}
